package view;

import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import model.bean.Produto;
import model.bean.Usuario;
import model.dao.ProdutoDAO;
import model.dao.UsuarioDAO;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author shouko3613
 */
public class CadastroView extends javax.swing.JFrame {

    /**
     * Creates new form CadView
     */
    public CadastroView() {
        initComponents();
        setTitle("Cadastro");
        setLocationRelativeTo(null);
        readProdTable();
        readUserTable();
        // ListaDep = new ArrayList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        ProdTable = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        QtdProdLabel = new javax.swing.JLabel();
        QtdProdText = new javax.swing.JTextField();
        PriceProdLabel = new javax.swing.JLabel();
        PriceProdText = new javax.swing.JTextField();
        CancelProdButton = new javax.swing.JButton();
        DescProdLabel = new javax.swing.JLabel();
        DescProdText = new javax.swing.JTextField();
        NewProdButton = new javax.swing.JButton();
        EditProdButton = new javax.swing.JButton();
        DelProdButton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        UserTable = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        NameUserLabel = new javax.swing.JLabel();
        NameUserText = new javax.swing.JTextField();
        EmailUserLabel = new javax.swing.JLabel();
        EmailUserText = new javax.swing.JTextField();
        CancelUserButton = new javax.swing.JButton();
        PassUserLabel = new javax.swing.JLabel();
        PassUserText = new javax.swing.JPasswordField();
        CEPUserLabel = new javax.swing.JLabel();
        CEPUserText = new javax.swing.JTextField();
        CityUserLabel = new javax.swing.JLabel();
        CityUserText = new javax.swing.JTextField();
        UFUserLabel = new javax.swing.JLabel();
        UFUserText = new javax.swing.JComboBox<>();
        DistrictUserLabel = new javax.swing.JLabel();
        DistrictUserText = new javax.swing.JTextField();
        StreetUserLabel = new javax.swing.JLabel();
        StreetUserText = new javax.swing.JTextField();
        NewUserButton = new javax.swing.JButton();
        EditUserButton = new javax.swing.JButton();
        DelUserButton = new javax.swing.JButton();
        SearchUserText = new javax.swing.JTextField();
        SearchUserButton = new javax.swing.JButton();
        AppBar = new javax.swing.JMenuBar();
        OptionsButtonBar = new javax.swing.JMenu();
        ExitButtonBar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ProdTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Descrição", "QTD", "Preço"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ProdTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProdTableMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(ProdTable);
        if (ProdTable.getColumnModel().getColumnCount() > 0) {
            ProdTable.getColumnModel().getColumn(0).setPreferredWidth(60);
            ProdTable.getColumnModel().getColumn(1).setPreferredWidth(250);
            ProdTable.getColumnModel().getColumn(2).setPreferredWidth(250);
            ProdTable.getColumnModel().getColumn(3).setPreferredWidth(80);
            ProdTable.getColumnModel().getColumn(3).setHeaderValue("Preço");
        }

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Dados"));

        QtdProdLabel.setText("Qtd:");

        PriceProdLabel.setText("Preço:");

        CancelProdButton.setText("Cancelar");
        CancelProdButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelProdButtonActionPerformed(evt);
            }
        });

        DescProdLabel.setText("Desc.:");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(QtdProdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(QtdProdText, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(PriceProdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PriceProdText, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(DescProdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DescProdText, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(252, 252, 252)
                .addComponent(CancelProdButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(QtdProdLabel)
                    .addComponent(QtdProdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PriceProdLabel)
                    .addComponent(PriceProdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DescProdLabel)
                    .addComponent(DescProdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(CancelProdButton)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        NewProdButton.setText("Novo");
        NewProdButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewProdButtonActionPerformed(evt);
            }
        });

        EditProdButton.setText("Editar");
        EditProdButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditProdButtonActionPerformed(evt);
            }
        });

        DelProdButton.setText("Excluir");
        DelProdButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DelProdButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(NewProdButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(EditProdButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(DelProdButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane5)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NewProdButton)
                    .addComponent(EditProdButton)
                    .addComponent(DelProdButton))
                .addGap(25, 25, 25)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Produtos", jPanel3);

        UserTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Email", "CEP", "Bairro", "Rua", "Cidade", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        UserTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UserTableMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(UserTable);
        if (UserTable.getColumnModel().getColumnCount() > 0) {
            UserTable.getColumnModel().getColumn(0).setPreferredWidth(30);
            UserTable.getColumnModel().getColumn(1).setPreferredWidth(100);
            UserTable.getColumnModel().getColumn(2).setPreferredWidth(100);
            UserTable.getColumnModel().getColumn(3).setPreferredWidth(100);
            UserTable.getColumnModel().getColumn(4).setPreferredWidth(100);
            UserTable.getColumnModel().getColumn(5).setPreferredWidth(100);
        }

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Dados"));

        NameUserLabel.setText("Nome:");

        NameUserText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                NameUserTextKeyReleased(evt);
            }
        });

        EmailUserLabel.setText("Email:");

        EmailUserText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailUserTextActionPerformed(evt);
            }
        });
        EmailUserText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                EmailUserTextKeyReleased(evt);
            }
        });

        CancelUserButton.setText("Cancelar");
        CancelUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelUserButtonActionPerformed(evt);
            }
        });

        PassUserLabel.setText("Senha:");

        CEPUserLabel.setText("CEP:");

        CityUserLabel.setText("Cidade:");

        CityUserText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CityUserTextActionPerformed(evt);
            }
        });

        UFUserLabel.setText("UF:");

        UFUserText.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione um estado", "RO", "AC", "AM", "RR", "PA", "AP", "TO", "MA", "PI", "CE", "RN", "PB", "PE", "AL", "SE", "BA", "MG", "ES", "RJ", "SP", "PR", "SC", "RS", "MS", "MT", "GO", "DF" }));

        DistrictUserLabel.setText("Bairro:");

        StreetUserLabel.setText("Rua:");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(UFUserLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UFUserText, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CancelUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(NameUserLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(NameUserText, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(EmailUserLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(EmailUserText, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(PassUserLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PassUserText, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(CEPUserLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CEPUserText, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DistrictUserLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DistrictUserText, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(StreetUserLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(StreetUserText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CityUserLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CityUserText, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameUserLabel)
                    .addComponent(NameUserText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmailUserLabel)
                    .addComponent(EmailUserText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PassUserLabel)
                    .addComponent(PassUserText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CEPUserLabel)
                    .addComponent(CEPUserText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CityUserLabel)
                    .addComponent(CityUserText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DistrictUserText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DistrictUserLabel)
                    .addComponent(StreetUserText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StreetUserLabel))
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(CancelUserButton)
                        .addContainerGap())
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(UFUserLabel)
                            .addComponent(UFUserText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        NewUserButton.setText("Novo");
        NewUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewUserButtonActionPerformed(evt);
            }
        });

        EditUserButton.setText("Editar");
        EditUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditUserButtonActionPerformed(evt);
            }
        });

        DelUserButton.setText("Excluir");
        DelUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DelUserButtonActionPerformed(evt);
            }
        });

        SearchUserText.setToolTipText("Buscar um Email");
        SearchUserText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                SearchUserTextKeyPressed(evt);
            }
        });

        SearchUserButton.setText("Buscar");
        SearchUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchUserButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(NewUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(EditUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(DelUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(SearchUserText, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SearchUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 20, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jScrollPane6)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NewUserButton)
                    .addComponent(EditUserButton)
                    .addComponent(DelUserButton)
                    .addComponent(SearchUserText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchUserButton))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Usuarios", jPanel5);

        OptionsButtonBar.setText("Opções");
        OptionsButtonBar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        OptionsButtonBar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        OptionsButtonBar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        ExitButtonBar.setText("Sair");
        ExitButtonBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonBarActionPerformed(evt);
            }
        });
        OptionsButtonBar.add(ExitButtonBar);

        AppBar.add(OptionsButtonBar);

        setJMenuBar(AppBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchUserButtonActionPerformed

        readSearchUserTable(SearchUserText.getText());

    }//GEN-LAST:event_SearchUserButtonActionPerformed

    private void SearchUserTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SearchUserTextKeyPressed

        if(evt.getKeyCode() == KeyEvent.VK_ENTER){

            readSearchUserTable(SearchUserText.getText());

        }

    }//GEN-LAST:event_SearchUserTextKeyPressed

    private void DelUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DelUserButtonActionPerformed

        if (UserTable.getSelectedRow() != -1) {

            //Delete Usuario
            Usuario user = new Usuario();
            UsuarioDAO userDao = new UsuarioDAO();

            user.setId((int) UserTable.getValueAt(UserTable.getSelectedRow(), 0));

            userDao.deleteUser(user);

            //Limpar campos apos exclusão dos dados
            NameUserText.setText("");
            EmailUserText.setText("");
            PassUserText.setText("");
            CEPUserText.setText("");
            DistrictUserText.setText("");
            StreetUserText.setText("");
            CityUserText.setText("");

            //Atualiza tabela
            readUserTable();

        } else {

            JOptionPane.showMessageDialog(null, "Selecione um usuario para ser excluido!");

        }
    }//GEN-LAST:event_DelUserButtonActionPerformed

    private void EditUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditUserButtonActionPerformed

        if (UserTable.getSelectedRow() != -1) {

            //Update Usuario
            Usuario user = new Usuario();
            UsuarioDAO userDao = new UsuarioDAO();

            user.setName(NameUserText.getText());
            user.setEmail(EmailUserText.getText());
            user.setCep(CEPUserText.getText());
            user.setBairro(DistrictUserText.getText());
            user.setRua(StreetUserText.getText());
            user.setCidade(CityUserText.getText());
            user.setEstado(UFUserText.getSelectedItem().toString());
            user.setId((int) UserTable.getValueAt(UserTable.getSelectedRow(), 0));

            userDao.updateUser(user);

            //Limpar campos apos atualização dos dados
            NameUserText.setText("");
            EmailUserText.setText("");
            PassUserText.setText("");
            CEPUserText.setText("");
            DistrictUserText.setText("");
            StreetUserText.setText("");
            CityUserText.setText("");

            //Atualiza tabela
            readUserTable();

        }
    }//GEN-LAST:event_EditUserButtonActionPerformed

    private void NewUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewUserButtonActionPerformed

        //Create Usuario
        Usuario user = new Usuario();
        UsuarioDAO userDao = new UsuarioDAO();

        if(!NameUserText.getText().trim().isEmpty() && !EmailUserText.getText().trim().isEmpty() && !PassUserText.getText().trim().isEmpty() && !CEPUserText.getText().trim().isEmpty() && !CityUserText.getText().trim().isEmpty() && !"Selecione um estado".equals(UFUserText.getSelectedItem().toString())){
            user.setName(NameUserText.getText());
            user.setEmail(EmailUserText.getText());
            user.setPassword(PassUserText.getText());
            user.setCep(CEPUserText.getText());
            user.setBairro(DistrictUserText.getText());
            user.setRua(StreetUserText.getText());
            user.setCidade(CityUserText.getText());
            user.setEstado(UFUserText.getSelectedItem().toString());

            userDao.createUser(user);

            //Limpar campos apos cadastro
            NameUserText.setText("");
            EmailUserText.setText("");
            PassUserText.setText("");
            CEPUserText.setText("");
            DistrictUserText.setText("");
            StreetUserText.setText("");
            CityUserText.setText("");

            //Adicionar novo produto a tabela
            readUserTable();
        } else {

            JOptionPane.showMessageDialog(null, "Preencha todos os campos");

        }
    }//GEN-LAST:event_NewUserButtonActionPerformed

    private void CancelUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelUserButtonActionPerformed

        //Limpar campos para cancelar a operação
        NameUserText.setText("");
        EmailUserText.setText("");
        PassUserText.setText("");
        CEPUserText.setText("");
        DistrictUserText.setText("");
        StreetUserText.setText("");
        CityUserText.setText("");
    }//GEN-LAST:event_CancelUserButtonActionPerformed

    private void UserTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserTableMouseClicked
        //Transfere os dados da linha para a linha
        if (UserTable.getSelectedRow() != -1) {

            NameUserText.setText(UserTable.getValueAt(UserTable.getSelectedRow(), 1).toString());
            EmailUserText.setText(UserTable.getValueAt(UserTable.getSelectedRow(), 2).toString());
            CEPUserText.setText(UserTable.getValueAt(UserTable.getSelectedRow(), 3).toString());
            DistrictUserText.setText(UserTable.getValueAt(UserTable.getSelectedRow(), 4).toString());
            StreetUserText.setText(UserTable.getValueAt(UserTable.getSelectedRow(), 5).toString());
            CityUserText.setText(UserTable.getValueAt(UserTable.getSelectedRow(), 6).toString());
            UFUserText.setSelectedItem(UserTable.getValueAt(UserTable.getSelectedRow(), 7).toString());
        }
    }//GEN-LAST:event_UserTableMouseClicked

    private void DelProdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DelProdButtonActionPerformed

        if (ProdTable.getSelectedRow() != -1) { 

            //Delete Produto
            Produto product = new Produto();
            ProdutoDAO productDao = new ProdutoDAO();

            product.setId((int) ProdTable.getValueAt(ProdTable.getSelectedRow(), 0));

            productDao.deleteProd(product);

            //Limpar campos apos exclusão dos dados
            DescProdText.setText("");
            QtdProdText.setText("");
            PriceProdText.setText("");

            //Atualiza tabela
            readProdTable();

        } else {

            JOptionPane.showMessageDialog(null, "Selecione um produto para ser excluido!");

        }
    }//GEN-LAST:event_DelProdButtonActionPerformed

    private void EditProdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditProdButtonActionPerformed

        if (ProdTable.getSelectedRow() != -1) {

            //Update Produto
            Produto product = new Produto();
            ProdutoDAO productDao = new ProdutoDAO();

            product.setDescription(DescProdText.getText());
            product.setQtd(Integer.parseInt(QtdProdText.getText()));
            product.setPrice(Double.parseDouble(PriceProdText.getText()));
            product.setId((int) ProdTable.getValueAt(ProdTable.getSelectedRow(), 0));

            productDao.updateProd(product);

            //Limpar campos apos atualização dos dados
            DescProdText.setText("");
            QtdProdText.setText("");
            PriceProdText.setText("");

            //Atualiza tabela
            readProdTable();

        }
    }//GEN-LAST:event_EditProdButtonActionPerformed

    private void NewProdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewProdButtonActionPerformed

        //Create Produto
        Produto product = new Produto();
        ProdutoDAO productDao = new ProdutoDAO();

        product.setDescription(DescProdText.getText());
        product.setQtd(Integer.parseInt(QtdProdText.getText()));
        product.setPrice(Double.parseDouble(PriceProdText.getText()));

        productDao.createProd(product);

        //Limpar campos apos cadastro
        DescProdText.setText("");
        QtdProdText.setText("");
        PriceProdText.setText("");

        //Adicionar novo produto a tabela
        readProdTable();
    }//GEN-LAST:event_NewProdButtonActionPerformed

    private void CancelProdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelProdButtonActionPerformed

        //Limpar campos para cancelar a operação
        DescProdText.setText("");
        QtdProdText.setText("");
        PriceProdText.setText("");
    }//GEN-LAST:event_CancelProdButtonActionPerformed

    private void ProdTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProdTableMouseClicked

        //Transfere os dados da linha para a linha
        if (ProdTable.getSelectedRow() != -1) {

            DescProdText.setText(ProdTable.getValueAt(ProdTable.getSelectedRow(), 1).toString());
            QtdProdText.setText(ProdTable.getValueAt(ProdTable.getSelectedRow(), 2).toString());
            PriceProdText.setText(ProdTable.getValueAt(ProdTable.getSelectedRow(), 3).toString());

        }
    }//GEN-LAST:event_ProdTableMouseClicked

    private void ExitButtonBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonBarActionPerformed
        new LoginView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ExitButtonBarActionPerformed

    private void NameUserTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NameUserTextKeyReleased
        NameUserText.setText(maxlength(NameUserText.getText(), 50));
    }//GEN-LAST:event_NameUserTextKeyReleased

    private void EmailUserTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EmailUserTextKeyReleased
        EmailUserText.setText(maxlength(EmailUserText.getText(), 250));
    }//GEN-LAST:event_EmailUserTextKeyReleased

    private void CityUserTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CityUserTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CityUserTextActionPerformed

    private void EmailUserTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailUserTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailUserTextActionPerformed

    public static String maxlength(String str, int maxValue){
        String value = str;
        if(str.length() > maxValue){
            JOptionPane.showMessageDialog(null, "Quantidade maxima atingida!");
            value = str.substring(0, maxValue);
        }
        return value;
    }
    
    public void readProdTable() {

        DefaultTableModel modelo = (DefaultTableModel) ProdTable.getModel();
        modelo.setNumRows(0);

        ProdutoDAO productDao = new ProdutoDAO();

        productDao.listProd().forEach(p -> {
            modelo.addRow(new Object[]{
                p.getId(),
                p.getDescription(),
                p.getQtd(),
                p.getPrice()
            });
        });

    }

    public void readUserTable() {

        DefaultTableModel modelo = (DefaultTableModel) UserTable.getModel();
        modelo.setNumRows(0);

        UsuarioDAO userDao = new UsuarioDAO();

        userDao.listUser().forEach(u -> {
            modelo.addRow(new Object[]{
                u.getId(),
                u.getName(),
                u.getEmail(),
                u.getCep(),
                u.getBairro(),
                u.getRua(),
                u.getCidade(),
                u.getEstado()
            });
        });

    }

    public void readSearchUserTable(String email) {

        DefaultTableModel modelo = (DefaultTableModel) UserTable.getModel();
        modelo.setNumRows(0);

        UsuarioDAO userDao = new UsuarioDAO();

        userDao.searchUser(email).forEach(u -> {
            modelo.addRow(new Object[]{
                u.getId(),
                u.getName(),
                u.getEmail(),
                u.getCep(),
                u.getBairro(),
                u.getRua(),
                u.getCidade(),
                u.getEstado()
            });
        });

    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar AppBar;
    private javax.swing.JLabel CEPUserLabel;
    private javax.swing.JTextField CEPUserText;
    private javax.swing.JButton CancelProdButton;
    private javax.swing.JButton CancelUserButton;
    private javax.swing.JLabel CityUserLabel;
    private javax.swing.JTextField CityUserText;
    private javax.swing.JButton DelProdButton;
    private javax.swing.JButton DelUserButton;
    private javax.swing.JLabel DescProdLabel;
    private javax.swing.JTextField DescProdText;
    private javax.swing.JLabel DistrictUserLabel;
    private javax.swing.JTextField DistrictUserText;
    private javax.swing.JButton EditProdButton;
    private javax.swing.JButton EditUserButton;
    private javax.swing.JLabel EmailUserLabel;
    private javax.swing.JTextField EmailUserText;
    private javax.swing.JMenuItem ExitButtonBar;
    private javax.swing.JLabel NameUserLabel;
    private javax.swing.JTextField NameUserText;
    private javax.swing.JButton NewProdButton;
    private javax.swing.JButton NewUserButton;
    private javax.swing.JMenu OptionsButtonBar;
    private javax.swing.JLabel PassUserLabel;
    private javax.swing.JPasswordField PassUserText;
    private javax.swing.JLabel PriceProdLabel;
    private javax.swing.JTextField PriceProdText;
    private javax.swing.JTable ProdTable;
    private javax.swing.JLabel QtdProdLabel;
    private javax.swing.JTextField QtdProdText;
    private javax.swing.JButton SearchUserButton;
    private javax.swing.JTextField SearchUserText;
    private javax.swing.JLabel StreetUserLabel;
    private javax.swing.JTextField StreetUserText;
    private javax.swing.JLabel UFUserLabel;
    private javax.swing.JComboBox<String> UFUserText;
    private javax.swing.JTable UserTable;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
